module.exports = {
  zero: [{
      "About": [{
        type: 'autogenerated',
        dirName: 'about',
      }],
      "Reference": [{
        type: 'autogenerated',
        dirName: 'reference',
      }],
      "Getting started": [{
        type: 'autogenerated',
        dirName: 'getting-started',
      }],
      "Concepts": [{
        type: 'autogenerated',
        dirName: 'concepts',
      }],
  },
  {
    type: 'category',
    label: 'Modules',
    collapsed: false,
    items: [
      {
        type: 'link',
        label: 'AWS EKS Stack',
        href: 'https://docs.zero-david.online/docs/modules/aws-eks-stack',
      },
      {
        type: 'link',
        label: 'Frontend',
        href: 'https://docs.zero-david.online/docs/modules/frontend',
      },
      {
        type: 'link',
        label: 'Backend',
        href: 'https://docs.zero-david.online/docs/modules/backend',
      }
    ]
  }]
}

