const config = require('./docusaurus.config');

module.exports = {
  zero: [{
      "About": [{
        type: 'autogenerated',
        dirName: 'about',
      }],
      "Getting started": [{
        type: 'autogenerated',
        dirName: 'getting-started',
      }],
      "Reference": [{
        type: 'autogenerated',
        dirName: 'reference',
      }],
    
      "Concepts": [{
        type: 'autogenerated',
        dirName: 'concepts',
      }],
  },
  {
    type: 'category',
    label: 'Modules',
    collapsed: false,
    items: [
      {
        type: 'link',
        label: 'AWS EKS Stack',
        href: `${config.url}/docs/modules/aws-eks-stack`,
      },
      {
        type: 'link',
        label: 'Frontend',
        href: `${config.url}/docs/modules/frontend-react`,
      },
      {
        type: 'link',
        label: 'Backend',
        href: `${config.url}/docs/modules/backend-go`,
      }
    ]
  }]
}

